--- #YAML:1.0
name: Locale-Object
version: 0.73
author:
  - Earle Martin <EMARTIN@cpan.org>
abstract: OO locale information
license: perl
requires:
  DBD::SQLite2: 0
  DBI: 0
  DateTime::TimeZone: 0.2505
  Scalar::Util: 1.1
  perl: 5.6.0
build_requires:
  Module::Build: 0.21
  Test::More: 0
  Test::Pod: 0
provides:
  Locale::Object:
    file: lib/Locale/Object.pm
    version: 0.73
  Locale::Object::Continent:
    file: lib/Locale/Object/Continent.pm
    version: 0.24
  Locale::Object::Country:
    file: lib/Locale/Object/Country.pm
    version: 0.35
  Locale::Object::Currency:
    file: lib/Locale/Object/Currency.pm
    version: 0.23
  Locale::Object::Currency::Converter:
    file: lib/Locale/Object/Currency/Converter.pm
    version: 0.12
  Locale::Object::DB:
    file: lib/Locale/Object/DB.pm
    version: 0.34
  Locale::Object::Language:
    file: lib/Locale/Object/Language.pm
    version: 0.132
generated_by: Module::Build version 0.25
