--- #YAML:1.0
name: Locale-Object
version: 0.53
license: perl
distribution_type: module
requires:
  DBD::SQLite: 0
  DBI: 0
  Finance::Currency::Convert::XE: 0
  Finance::Currency::Convert::Yahoo: 0
  Scalar::Util: 0.1
  perl: 5.6.0
recommends: {}
build_requires:
  Module::Build: 0.21
  Test::More: 0
  Test::Pod: 0
conflicts: {}
provides:
  Locale::Object:
    file: lib/Locale/Object.pm
    version: 0.53
  Locale::Object::Continent:
    file: lib/Locale/Object/Continent.pm
    version: 0.23
  Locale::Object::Country:
    file: lib/Locale/Object/Country.pm
    version: 0.32
  Locale::Object::Currency:
    file: lib/Locale/Object/Currency.pm
    version: 0.22
  Locale::Object::Currency::Converter:
    file: lib/Locale/Object/Currency/Converter.pm
    version: 0.11
  Locale::Object::DB:
    file: lib/Locale/Object/DB.pm
    version: 0.31
  Locale::Object::DB::Schemata:
    file: lib/Locale/Object/DB/Schemata.pm
    version: 0.31
  Locale::Object::Language:
    file: lib/Locale/Object/Language.pm
    version: 0.12
generated_by: Module::Build version 0.21
